fix: revert "feat(feeshare): Developer Incentives (#144)"
classic-terra/core pull request #268
Opened 2023-06-17 17:56 UTC by inon-man

This reverts commit 1e7936c622a6519596d302a8970b6f684ebd282b. This PR also includes orphan branch v2.1.1 adoption.

## Summary of changes
Fixes: #267 

----

## (FOR ADMIN) Before merging

- [ ] Added appropriate labels to PR
- [ ] Squashed all commits, uses message "Merge pull request #XYZ: [title]" (coding standards)
- [ ] Confirm added tests are consistent with the intended behavior of changes
- [ ] Ensure all tests pass

2023-06-18 09:59 UTC, fragwuerdig requested changes
I'd rather keep `x/feeshare` directory.

2023-06-18 09:59 UTC, fragwuerdig commented on x/feeshare/keeper/keeper.go
Can we keep the `x/feeshare` folder for future use and just de-wire the module?

2023-06-18 09:59 UTC, fragwuerdig commented on scripts/run-node.sh
What you mean exactly? I am happy with renaming `HOME` to `HOME_DIR`

2023-06-18 09:59 UTC, fragwuerdig commented on proto/terra/feeshare/v1beta1/feeshare.proto
We should keep the `proto/terra/feeshare` folder for future use. no?

2023-06-18 09:59 UTC, fragwuerdig commented on custom/wasm/keeper/handler_plugin.go
This is linting fix?

2023-06-18 09:59 UTC, fragwuerdig commented on x/feeshare/keeper/testdata/reflect.wasm
We need this occasionally for local tests. Please, do not remove.

2023-06-18 13:24 UTC, fragwuerdig commented on x/feeshare/keeper/keeper.go
Ok.

2023-06-18 13:26 UTC, fragwuerdig commented on proto/terra/feeshare/v1beta1/feeshare.proto
Resolved

2023-06-18 13:27 UTC, fragwuerdig commented on x/feeshare/keeper/testdata/reflect.wasm
Ok.

2023-06-19 03:38 UTC, nghuyenthevinh2000 commented on x/feeshare/keeper/testdata/reflect.wasm
I agree with inon-man, reflect.wasm can stay in contrib or script folder

2023-06-19 03:49 UTC, nghuyenthevinh2000 approved these changes

2023-06-19 06:04 UTC, fragwuerdig approved these changes

2023-06-19 06:26 UTC, merged