fix: set min commission back to 5%
classic-terra/core pull request #349
Opened 2023-09-15 22:20 UTC by fragwuerdig

Dear L1 Team. During the mainnet upgrade the min. validator commission was accidentally set to 0%. This immediately led to creation of 0% validators and also validators lowering their commissions. Simple governance proposal to set the commission to 5% is _not_ sufficient. This is why I prepared this fix to be applied as fork guard or hotfix upgrade (meaning: it's a state machine breaking upgrade, but due to a fork guard validators can install without chain halt).

I suggest to test it on rebel-2 first.

**TODO**: Coordinate/Communication on proper fork block heights.

2023-09-15 22:36 UTC, MattsMarket commented
Good job frag!

2023-09-16 05:58 UTC, fragwuerdig commented
Marked as blocked until we agree on the block heights. I would suggest the following

- rebel-2: `16,215,600` - Tue, 19 Sept, 10:00am UTC
- columbus-5: `14,650,370` - Fri, 22 Sept, 10:00am

2023-09-18 07:48 UTC, nghuyenthevinh2000 requested changes
Not looking good through initial testing on my machine

Will debug further

<img width="1512" alt="Screenshot 2023-09-18 at 14 47 37" src="https://github.com/classic-terra/core/assets/23058164/92d14d8a-2de2-4833-95d0-3b726c6193d9">

2023-09-18 07:58 UTC, nghuyenthevinh2000 commented
working now

<img width="1136" alt="Screenshot 2023-09-18 at 14 57 43" src="https://github.com/classic-terra/core/assets/23058164/bbf5c828-eccc-4995-bd00-d8754f6a8fd8">

2023-09-18 07:59 UTC, nghuyenthevinh2000 requested changes
Need to go through text fork proposal to notify validators of this change

2023-09-21 07:32 UTC, nghuyenthevinh2000 approved these changes

2023-09-21 07:32 UTC, merged