build(deps): Bump ibc-go from 7.4.0 to 7.4.1
classic-terra/core pull request #506
Opened 2024-07-31 07:09 UTC by inon-man

## Summary of changes

Bumps ibc-go and go version

----

## (FOR ADMIN) Before merging

- [x] Added appropriate labels to PR
- [x] Squashed all commits, uses message "Merge pull request #XYZ: [title]" (coding standards)
- [ ] Confirm added tests are consistent with the intended behavior of changes
- [ ] Ensure all tests pass

2024-07-31 08:31 UTC, fragwuerdig reviewed
Looks good from my side. Thanks for the contribution! I presume this is a state machine breaking upgrade, is it not? In this case due to the decentralized nature of Terra Classic the current "standard procedure" to do such an upgrade is to force a chain halt through an upgrade proposal and then install the new client with an empty upgrade handler in place... In this case the PR would lack of an upgrade handler... Maybe you can give a bit feedback on this matter?

2024-07-31 11:01 UTC, phamminh0811 requested changes

2024-07-31 11:01 UTC, phamminh0811 commented on go.mod
It will not work, as we use https://github.com/classic-terra/core/blob/c8c04d900f0b93c263723bfe7257598f0460316a/go.mod#L233

2024-08-01 15:49 UTC, inon-man commented on go.mod
Resolved

2024-08-01 15:50 UTC, inon-man commented
> Looks good from my side. Thanks for the contribution! I presume this is a state machine breaking upgrade, is it not? In this case due to the decentralized nature of Terra Classic the current "standard procedure" to do such an upgrade is to force a chain halt through an upgrade proposal and then install the new client with an empty upgrade handler in place... In this case the PR would lack of an upgrade handler... Maybe you can give a bit feedback on this matter?

I think there are no breaking changes. See https://github.com/cosmos/ibc-go/blob/v7.4.1/CHANGELOG.md#v741---2024-05-22

2024-08-01 23:46 UTC, inon-man commented
Emitting events doesn't break the state.

2024-08-01 23:46 UTC, inon-man commented
> > There are no breaking changes. See https://github.com/cosmos/ibc-go/blob/v7.4.1/CHANGELOG.md#v741---2024-05-22
> 
> When looking at the code diffs from 7.4.0 I would assume it could be state breaking due to different handling of events.
Emitting events doesn't break the state. You can test it by adding any events after any messages

2024-08-02 01:03 UTC, inon-man commented
I don't think these should be applied immediately. I was thinking about making them included by governance in the future.

2024-08-02 05:11 UTC, phamminh0811 approved these changes

2025-05-09 10:05 UTC, fragwuerdig commented
closed - outdated

2025-05-09 10:05 UTC, closed without merging